version: '3.7'

x-app: &x-app
  image: mpn-discord-bot
  restart: always
  build:
    dockerfile: docker/Dockerfile
    context: .

services:
  app:
    <<: *x-app
    expose:
      - '3001'
    ports:
      - '3001:3001'
    volumes:
      - .:/home/app/mpn-discord-bot
    env_file: .env

  compile:
    <<: *x-app
    command: yarn compile:dev
    working_dir: $PWD
